apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: osu-efa-test-ompi
spec:
  slotsPerWorker: 72
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
          - image: quay.io/cgament/mpi:efa-sshd
            imagePullPolicy: Always
            name: osu-efa-test-launcher
            env:
            - name: PATH
              value: "/opt/amazon/openmpi/bin:/opt/amazon/efa/bin/:$PATH"
            - name: LD_LIBRARY_PATH
              value: "/opt/amazon/openmpi/lib64:/opt/amazon/efa/lib64:$LD_LIBRARY_PATH"
            - name: I_MPI_DEBUG
              value: "2000"
            command:
              - /opt/amazon/openmpi/bin/mpirun
              - --allow-run-as-root
              - -np
              - "2"
              - -verbose
              - -N
              - "1"
              - -x
              - PATH
              - -x
              - LD_LIBRARY_PATH
              - --map-by
              - slot
              - -mca
              - plm_rsh_agent
              - /usr/bin/ssh
#              - /tmp/osu-micro-benchmarks-5.7.1/mpi/pt2pt/osu_latency
              # To verify EFA device is working properly comment out line above and uncomment 3 lines below
              - /opt/amazon/efa/bin/fi_info
              - -p
              - efa
    Worker:
      replicas: 2
      template:
        spec:
          hostNetwork: true
          containers:
          - image: quay.io/cgament/mpi:efa-sshd
            name: osu-efa-test-ompi-worker
            imagePullPolicy: Always
            resources:
              limits:
                hugepages-2Mi: 5120Mi
                memory: 154000Mi
                vpc.amazonaws.com/efa: 1
              requests:
                memory: 154000Mi
                vpc.amazonaws.com/efa: 1
