apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: osu-efa-test-intel
  namespace: default
spec:
  slotsPerWorker: 72
  cleanPodPolicy: Running
  mpiDistribution: IntelMPI
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          hostNetwork: true
          imagePullPolicy: Always
          restartPolicy: OnFailure
          containers:
          - image: quay.io/cgament/mpi:intel
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
            name: osu-efa-intel-launcher
            env:
            - name: I_MPI_DEBUG
              value: "5"
            - name: FI_LOG_LEVEL
              value: "5"
            - name: I_MPI_SHM
              value: "off"
            command:
            - /opt/intel/oneapi/mpi/2021.3.0/bin/mpirun
            - -n
            - "2"
            - -ppn
            - "1"
            - /tmp/osu-micro-benchmarks-5.7.1/mpi/pt2pt/osu_latency
            # To verify EFA device is working properly comment out line above and uncomment 3 lines below
            #- /opt/amazon/efa/bin/fi_info
            #- -p
            #- efa
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
    Worker:
      replicas: 2
      template:
        spec:
          hostNetwork: true
          imagePullPolicy: Always
          containers:
          - image: quay.io/cgament/mpi:intel
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
            name: osu-efa-intel-worker-ping
            resources:
              limits:
                hugepages-2Mi: 5120Mi
                memory: 154000Mi
                vpc.amazonaws.com/efa: 1
              requests:
                memory: 154000Mi
                vpc.amazonaws.com/efa: 1
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
